# Copyright (c) 2026 secp contributors
# SPDX-License-Identifier: MIT
"""bitcoin: A pure-Python ECDSA signing, extraction, and analysis library.

This top-level package re-exports the library's public API so that users
can write ``import bitcoin`` and reach any supported feature without
chasing submodules.  The package is intentionally organised around a
layered architecture:

- :mod:`bitcoin.curve` – secp256k1 arithmetic, point type, pluggable
  backends (pure Python and optional ``coincurve``/libsecp256k1).
- :mod:`bitcoin.field` – modular-arithmetic primitives (inverse,
  square root) shared by the curve layer.
- :mod:`bitcoin.encoding` – low-level binary helpers: hex, varint,
  DER, SEC public-key encoding, and Bitcoin hash functions
  (SHA-256, double-SHA-256, HASH-160, BIP-340 tagged hash).
- :mod:`bitcoin.script` – script parsing, classification (P2PK,
  P2PKH, P2SH, P2WPKH, P2WSH, P2TR, multisig, timelock),
  construction, and Taproot script-path helpers.
- :mod:`bitcoin.sighash` – signature-hash computation for legacy,
  SegWit v0 (BIP-143), and Taproot (BIP-341) transactions, plus
  SIGHASH flag constants.
- :mod:`bitcoin.transaction` – immutable transaction models, wire
  parser, fluent builder, RBF detection, fee estimation, and
  sighash/RBF/serialisation engines bound to ``Tx``.
- :mod:`bitcoin.signature` – ECDSA and Schnorr (BIP-340) signature
  extraction, linearisation (canonical sorting), verification,
  signing, batch extraction pipelines, and nonce-reuse attack
  utilities.
- :mod:`bitcoin.descriptor` – Miniscript descriptor parser/compiler
  and analyzer (subset of the Miniscript language).
- :mod:`bitcoin.psbt` – Partially Signed Bitcoin Transaction (BIP-174)
  parsing, serialisation, in-memory editor, and signature extraction.
- :mod:`bitcoin.services` – blockchain data providers (Blockstream,
  Mempool.space, blockchain.info, generic HTTP), transaction
  serialisation helpers, and async/batch fetching.
- :mod:`bitcoin.cli` – Typer-based command-line interface exposing
  the most common operations.

Design notes
------------
- Pure-Python by default; libsecp256k1 is opt-in via the
  ``coincurve`` extra.  See :data:`bitcoin.settings.settings` for the
  ``default_backend`` knob.
- No network dependencies at the core layer; blockchain services are
  isolated in :mod:`bitcoin.services` and are never imported by the
  signature or script modules.
- All public dataclasses are ``frozen=True, slots=True`` for value
  semantics and predictable hashing.
"""

__version__ = "0.4.0"

from bitcoin.curve import (
    CURVE_A,
    CURVE_B,
    CURVE_ORDER,
    FIELD_PRIME,
    GENERATOR,
    GENERATOR_X,
    GENERATOR_Y,
    INFINITY,
    CurveBackend,
    LibsecpBackend,
    NativeBackend,
    Point,
    add,
    batch_normalize,
    batch_validate,
    double,
    get_backend,
    is_on_curve,
    multi_multiply,
    multiply,
    negate,
    normalize,
    normalize_non_negative,
    parse_public_key,
    serialize_public_key,
    set_backend,
    sqrt_field,
)
from bitcoin.descriptor import (
    ESTIMATED_SATISFACTION,
    DescriptorError,
    DescriptorInfo,
    DescriptorNode,
    analyze_descriptor,
    collect_info,
    collect_keys,
    compile_descriptor,
    contains_op,
    emit_script,
    estimate_satisfaction,
    extract_keys,
    sorted_unique,
    split_args,
)
from bitcoin.encoding import (
    bytes_to_int,
    decode_der,
    decode_hex,
    decode_varint,
    encode_der,
    encode_hex,
    encode_varint,
    hash160,
    hash256,
    int_to_bytes,
    parse_sec,
    serialize_sec,
    sha256,
    tagged_hash,
)
from bitcoin.exceptions import (
    BitcoinError,
    NotInvertible,
    ParsingError,
    PointError,
    UnsupportedScriptPathError,
)
from bitcoin.field import inverse, pow_mod, sqrt, validate_non_negative
from bitcoin.psbt import (
    Psbt,
    PsbtEditor,
    PsbtInput,
    PsbtOutput,
    parse_keypath_value,
    parse_psbt,
    parse_psbt_from_file,
    parse_psbt_hex,
    parse_psbt_impl,
    parse_psbt_worker,
    process_psbt_batch,
    process_psbt_batch_with,
    psbt_extract_signatures,
    serialize_psbt,
)
from bitcoin.script import (
    MULTISIG,
    NON_STANDARD,
    OP_0,
    OP_1,
    OP_1NEGATE,
    OP_16,
    OP_CHECKLOCKTIMEVERIFY,
    OP_CHECKMULTISIG,
    OP_CHECKSEQUENCEVERIFY,
    OP_CHECKSIG,
    OP_DUP,
    OP_EQUAL,
    OP_EQUALVERIFY,
    OP_HASH160,
    OP_PUSHDATA1,
    OP_PUSHDATA2,
    OP_PUSHDATA4,
    OP_RETURN,
    OPCODES_BY_NAME,
    OPCODES_BY_VALUE,
    P2PK,
    P2PKH,
    P2SH,
    P2TR,
    P2WPKH,
    P2WSH,
    TIMELOCK,
    TaprootControlBlock,
    TaprootScriptPath,
    build_p2pk,
    build_p2pkh,
    build_p2sh,
    build_p2tr,
    build_p2wpkh,
    build_p2wsh,
    classify_detailed,
    classify_script_pubkey,
    classify_script_sig,
    compute_tapleaf_hash,
    compute_tweak,
    get_key_path_signature,
    get_x_only_pubkey,
    has_timelocks,
    is_bare_multisig,
    is_key_path_spend,
    is_op_return,
    is_valid_leaf_version,
    make_p2pkh_script,
    parse_control_block,
    parse_script,
    parse_taproot_witness_stack,
    serialize_script,
)
from bitcoin.services import (
    BlockchainInfoProvider,
    BlockchainProvider,
    BlockstreamProvider,
    GenericHttpProvider,
    MempoolSpaceProvider,
    async_batch_fetch_transactions,
    async_enrich_transaction,
    batch_enrich_transactions,
    batch_fetch_transactions,
    broadcast_transaction,
    enrich_transaction,
    fetch_and_extract,
    serialize_legacy_tx,
    serialize_tx,
    tx_to_json,
)
from bitcoin.settings import settings
from bitcoin.sighash import (
    SIGHASH_ALL,
    SIGHASH_ALL_ANYONECANPAY,
    SIGHASH_ANYONECANPAY,
    SIGHASH_MASK,
    SIGHASH_NAMES,
    SIGHASH_NONE,
    SIGHASH_NONE_ANYONECANPAY,
    SIGHASH_SINGLE,
    SIGHASH_SINGLE_ANYONECANPAY,
    require_sighash_flag,
    sighash_legacy,
    sighash_name,
    sighash_segwit,
    sighash_taproot,
)
from bitcoin.signature import (
    Record,
    SignatureCollection,
    batch_extract,
    batch_extract_from_file,
    batch_verify,
    correlate_across_transactions,
    extract_signatures,
    linearize_signatures,
    merge_records,
    recover_public_key,
    sign,
    sign_tx_input,
    verify_all,
    verify_schnorr_sig,
    verify_sig,
)
from bitcoin.transaction import (
    EMPTY_WITNESS,
    OutPoint,
    TransactionBuilder,
    Tx,
    TxIn,
    TxOut,
    Witness,
    estimate_minimum_fee,
    estimate_optimal_fee,
    estimate_vsize,
    has_sequence_lock,
    is_opt_in_rbf,
    make_tx,
    parse_tx,
    total_output_value,
    tx_from_dict,
)

__all__ = [
    "BitcoinError",
    "BlockchainInfoProvider",
    "BlockchainProvider",
    "BlockstreamProvider",
    "CurveBackend",
    "CURVE_A",
    "CURVE_B",
    "CURVE_ORDER",
    "DescriptorError",
    "DescriptorInfo",
    "DescriptorNode",
    "EMPTY_WITNESS",
    "ESTIMATED_SATISFACTION",
    "FIELD_PRIME",
    "GENERATOR",
    "GENERATOR_X",
    "GENERATOR_Y",
    "GenericHttpProvider",
    "INFINITY",
    "LibsecpBackend",
    "MULTISIG",
    "MempoolSpaceProvider",
    "NON_STANDARD",
    "NativeBackend",
    "NotInvertible",
    "OP_0",
    "OP_1",
    "OP_16",
    "OP_1NEGATE",
    "OP_CHECKLOCKTIMEVERIFY",
    "OP_CHECKMULTISIG",
    "OP_CHECKSEQUENCEVERIFY",
    "OP_CHECKSIG",
    "OP_DUP",
    "OP_EQUAL",
    "OP_EQUALVERIFY",
    "OP_HASH160",
    "OP_PUSHDATA1",
    "OP_PUSHDATA2",
    "OP_PUSHDATA4",
    "OP_RETURN",
    "OPCODES_BY_NAME",
    "OPCODES_BY_VALUE",
    "OutPoint",
    "P2PK",
    "P2PKH",
    "P2SH",
    "P2TR",
    "P2WPKH",
    "P2WSH",
    "ParsingError",
    "Point",
    "PointError",
    "Psbt",
    "PsbtEditor",
    "PsbtInput",
    "PsbtOutput",
    "Record",
    "SIGHASH_ALL",
    "SIGHASH_ALL_ANYONECANPAY",
    "SIGHASH_ANYONECANPAY",
    "SIGHASH_MASK",
    "SIGHASH_NAMES",
    "SIGHASH_NONE",
    "SIGHASH_NONE_ANYONECANPAY",
    "SIGHASH_SINGLE",
    "SIGHASH_SINGLE_ANYONECANPAY",
    "SignatureCollection",
    "TIMELOCK",
    "TaprootControlBlock",
    "TaprootScriptPath",
    "TransactionBuilder",
    "Tx",
    "TxIn",
    "TxOut",
    "UnsupportedScriptPathError",
    "Witness",
    "add",
    "analyze_descriptor",
    "async_batch_fetch_transactions",
    "async_enrich_transaction",
    "batch_enrich_transactions",
    "batch_extract",
    "batch_extract_from_file",
    "batch_fetch_transactions",
    "batch_normalize",
    "batch_validate",
    "batch_verify",
    "broadcast_transaction",
    "build_p2pk",
    "build_p2pkh",
    "build_p2sh",
    "build_p2tr",
    "build_p2wpkh",
    "build_p2wsh",
    "bytes_to_int",
    "classify_detailed",
    "classify_script_pubkey",
    "classify_script_sig",
    "collect_info",
    "collect_keys",
    "compile_descriptor",
    "compute_tapleaf_hash",
    "compute_tweak",
    "contains_op",
    "correlate_across_transactions",
    "decode_der",
    "decode_hex",
    "decode_varint",
    "double",
    "emit_script",
    "encode_der",
    "encode_hex",
    "encode_varint",
    "enrich_transaction",
    "estimate_satisfaction",
    "estimate_minimum_fee",
    "estimate_optimal_fee",
    "estimate_vsize",
    "extract_keys",
    "extract_signatures",
    "fetch_and_extract",
    "get_backend",
    "get_key_path_signature",
    "get_x_only_pubkey",
    "has_sequence_lock",
    "has_timelocks",
    "hash160",
    "hash256",
    "int_to_bytes",
    "inverse",
    "is_bare_multisig",
    "is_key_path_spend",
    "is_on_curve",
    "is_op_return",
    "is_opt_in_rbf",
    "is_valid_leaf_version",
    "linearize_signatures",
    "make_p2pkh_script",
    "make_tx",
    "merge_records",
    "multi_multiply",
    "multiply",
    "negate",
    "normalize",
    "normalize_non_negative",
    "parse_control_block",
    "parse_keypath_value",
    "parse_psbt",
    "parse_psbt_from_file",
    "parse_psbt_hex",
    "parse_psbt_impl",
    "parse_psbt_worker",
    "parse_public_key",
    "parse_sec",
    "parse_script",
    "parse_taproot_witness_stack",
    "parse_tx",
    "pow_mod",
    "process_psbt_batch",
    "process_psbt_batch_with",
    "psbt_extract_signatures",
    "recover_public_key",
    "require_sighash_flag",
    "serialize_legacy_tx",
    "serialize_psbt",
    "serialize_public_key",
    "serialize_sec",
    "serialize_script",
    "serialize_tx",
    "set_backend",
    "settings",
    "sha256",
    "sighash_legacy",
    "sighash_name",
    "sighash_segwit",
    "sighash_taproot",
    "sign",
    "sign_tx_input",
    "sorted_unique",
    "split_args",
    "sqrt",
    "sqrt_field",
    "tagged_hash",
    "total_output_value",
    "tx_from_dict",
    "tx_to_json",
    "validate_non_negative",
    "verify_all",
    "verify_schnorr_sig",
    "verify_sig",
]
